//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Excelsior.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Excelsior.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release v4.0.26.1.
        /// </summary>
        internal static string appVersion {
            get {
                return ResourceManager.GetString("appVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browser {
            get {
                object obj = ResourceManager.GetObject("Browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carljordee11@gmail.com.
        /// </summary>
        internal static string carlEmail {
            get {
                return ResourceManager.GetString("carlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAW {
            get {
                object obj = ResourceManager.GetObject("CAW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CAW_Icon_old {
            get {
                object obj = ResourceManager.GetObject("CAW_Icon_old", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAW_old {
            get {
                object obj = ResourceManager.GetObject("CAW_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dropbox.com/.
        /// </summary>
        internal static string dropBoxURL {
            get {
                return ResourceManager.GetString("dropBoxURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gcash {
            get {
                object obj = ResourceManager.GetObject("gcash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.geogebra.org/calculator.
        /// </summary>
        internal static string geogebraURL {
            get {
                return ResourceManager.GetString("geogebraURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mail.google.com/.
        /// </summary>
        internal static string gmailURL {
            get {
                return ResourceManager.GetString("gmailURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://classroom.google.com/.
        /// </summary>
        internal static string googleClassroomURL {
            get {
                return ResourceManager.GetString("googleClassroomURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/.
        /// </summary>
        internal static string googleDocsURL {
            get {
                return ResourceManager.GetString("googleDocsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/.
        /// </summary>
        internal static string googleDriveURL {
            get {
                return ResourceManager.GetString("googleDriveURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://meet.google.com/.
        /// </summary>
        internal static string googleMeetURL {
            get {
                return ResourceManager.GetString("googleMeetURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://scholar.google.com/.
        /// </summary>
        internal static string googleScholarURL {
            get {
                return ResourceManager.GetString("googleScholarURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://outlook.live.com/.
        /// </summary>
        internal static string hotmailURL {
            get {
                return ResourceManager.GetString("hotmailURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.icloud.com/mail.
        /// </summary>
        internal static string icloudMailURL {
            get {
                return ResourceManager.GetString("icloudMailURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://imgur.com/.
        /// </summary>
        internal static string imgurlURL {
            get {
                return ResourceManager.GetString("imgurlURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lucid.app/.
        /// </summary>
        internal static string lucidChartsURL {
            get {
                return ResourceManager.GetString("lucidChartsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mediafire.com/.
        /// </summary>
        internal static string mediafireURL {
            get {
                return ResourceManager.GetString("mediafireURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mega.io/.
        /// </summary>
        internal static string megaURL {
            get {
                return ResourceManager.GetString("megaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.merriam-webster.com/.
        /// </summary>
        internal static string merriamURL {
            get {
                return ResourceManager.GetString("merriamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.office.com/.
        /// </summary>
        internal static string microsoftOfficeLiveURL {
            get {
                return ResourceManager.GetString("microsoftOfficeLiveURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.live.com/.
        /// </summary>
        internal static string microsoftTeamsURL {
            get {
                return ResourceManager.GetString("microsoftTeamsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://svcc.neolms.com.
        /// </summary>
        internal static string neoLMSURL {
            get {
                return ResourceManager.GetString("neoLMSURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;title&gt;&lt;/title&gt;
        ///  &lt;link href=&quot;style.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///  &lt;script src=&quot;http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script&gt;
        ///  &lt;/script&gt;
        ///
        ///&lt;a class=&quot;twitter-timeline&quot; href=&quot;https://twitter.com/DJZKOfficial?ref_src=twsrc%5Etfw&quot;&gt;Tweets by DJZKOfficial&lt;/a&gt; &lt;script async src=&quot;https://platform.twitter.com/widgets.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string newsString {
            get {
                return ResourceManager.GetString("newsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.omnicalculator.com/.
        /// </summary>
        internal static string omniCalculatorURL {
            get {
                return ResourceManager.GetString("omniCalculatorURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onedrive.live.com/.
        /// </summary>
        internal static string oneDriveURL {
            get {
                return ResourceManager.GetString("oneDriveURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pastebin.com/.
        /// </summary>
        internal static string pastebinURL {
            get {
                return ResourceManager.GetString("pastebinURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://apkpure.com/developer?id=1762054.
        /// </summary>
        internal static string pcsApkPureURL {
            get {
                return ResourceManager.GetString("pcsApkPureURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/Sbcjproductionsmcexe.
        /// </summary>
        internal static string pcsFacebookURL {
            get {
                return ResourceManager.GetString("pcsFacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.freepdfconvert.com/.
        /// </summary>
        internal static string pdfConverterURL {
            get {
                return ResourceManager.GetString("pdfConverterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pixel_Cowboy {
            get {
                object obj = ResourceManager.GetObject("Pixel_Cowboy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.researchgate.net/.
        /// </summary>
        internal static string researchGateURL {
            get {
                return ResourceManager.GetString("researchGateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.scribd.com/.
        /// </summary>
        internal static string scribdURL {
            get {
                return ResourceManager.GetString("scribdURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.slideshare.net/.
        /// </summary>
        internal static string sildeshareURL {
            get {
                return ResourceManager.GetString("sildeshareURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://streamable.com/.
        /// </summary>
        internal static string streamableURL {
            get {
                return ResourceManager.GetString("streamableURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SVCC_Icon_Fixed {
            get {
                object obj = ResourceManager.GetObject("SVCC_Icon_Fixed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SVCC_Logo_Fixed {
            get {
                object obj = ResourceManager.GetObject("SVCC_Logo_Fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SVCC_Logo_Fixed_Contrast {
            get {
                object obj = ResourceManager.GetObject("SVCC_Logo_Fixed_Contrast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SVCC_Logo_Fixed_Contrast_2 {
            get {
                object obj = ResourceManager.GetObject("SVCC_Logo_Fixed_Contrast_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SVCC_Logo_Fixed_Contrast_3 {
            get {
                object obj = ResourceManager.GetObject("SVCC_Logo_Fixed_Contrast_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svccregistrar@gmail.com.
        /// </summary>
        internal static string svccEmail {
            get {
                return ResourceManager.GetString("svccEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/svcccabuyaoofficial/.
        /// </summary>
        internal static string svccFacebookURL {
            get {
                return ResourceManager.GetString("svccFacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stvincentcollege.edu.ph/.
        /// </summary>
        internal static string svccHomePage {
            get {
                return ResourceManager.GetString("svccHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://svccsystem.com/.
        /// </summary>
        internal static string svccSystemURL {
            get {
                return ResourceManager.GetString("svccSystemURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mail.yahoo.com.
        /// </summary>
        internal static string yahooMailURL {
            get {
                return ResourceManager.GetString("yahooMailURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zippyshare.com/.
        /// </summary>
        internal static string zippyshareURL {
            get {
                return ResourceManager.GetString("zippyshareURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emperorxizzle99@gmail.com.
        /// </summary>
        internal static string zkEmail {
            get {
                return ResourceManager.GetString("zkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/DJZK.
        /// </summary>
        internal static string zkGithubURL {
            get {
                return ResourceManager.GetString("zkGithubURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zoom.us/join.
        /// </summary>
        internal static string zoomURL {
            get {
                return ResourceManager.GetString("zoomURL", resourceCulture);
            }
        }
    }
}
